
spring:
  datasource:
    url: jdbc:mariadb://54.86.217.188:3306/MaPDuck
    driver-class-name: org.mariadb.jdbc.Driver
    username: mapduck
    password: mapduck2021
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 9000